perform_sweep: True
parameter_space:
  seed: !sweep
    default: 1
    range: [8]
  num_epochs: 30
  RC_model:

    # Settings for the neural network
    NeuralNet:
      type: mlp
      lookback: 96 #amount of timesteps input for param estimation | 4 or 96

      num_layers: 2 
      nodes_per_layer:
        default: 140
      learning_rate: 0.0029
      optimizer: Adam

    # Settings for the training
    Training:
      train_range: [0, 960] #use 10 days of data for training
      test_range: [960, 1152] # and the following 2 days for testing
      mode: predict


      model_type: RC
      slicing_difference: 96
      loss_function:
        name: RMSELoss
        kwargs:
          reduction: sum
      device: cpu
      num_threads: ~

      # Can scale parameters here
      scaling_factors:
        C: 1.0e7 
        R: 1.0e-3
        A_eff: 10
