# to be tested
# datensätze (builda, real)
# RC, TiTe
# NeuralNet, optimizer (best, bayesian), GA(best, bayesian)

perform_sweep: True
parameter_space:
  seed: 0
  num_epochs: 20
  RC_model:
    Data:
      dt: 900
      load_from_dir:
        path: !sweep
          default: data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T1
          values:
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T1
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T2
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T3
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T4
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T5
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T6
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T7
            - data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/T8
            - data/RC_model/ds4_formatted_Builda_cols.csv
        csv_keys: [thermalZone.TAir, weaBus.TDryBul, totalHeatingPower.y, weaDat.weaBus.HGloHor]
        effWinArea: 1
        subset: 8640 # 3monate

    # Settings for the neural network
    NeuralNet:
      type: mlp
      lookback: 96 #amount of timesteps input for param estimation | 4 or 96

      num_layers: 2 # TUNING (2..5, 1er steps)
      nodes_per_layer:
        default: 140 # TUNING (20..200, 20er steps)
      biases:
        default: [0, 1]
      activation_funcs:
        default: sigmoid #TUNING? - try relu/alpharelu
        layer_specific:
          -1: abs
      learning_rate: 0.0029 # TUNING (0.0001.. 0.005, log steps)
      optimizer: Adam
      prior:
        distribution: uniform
        parameters:
          lower: 0
          upper: 1

    # Settings for the training
    Training:
      train_range: 0.6
      val_range: 0.2
      test_range: [6912, 8640]
      mode: predict


      model_type: TwoR2C
      slicing_difference: 96
      loss_function:
        name: RMSELoss
        kwargs:
          reduction: sum
      device: cpu
      num_threads: ~

      # Can scale parameters here
      scaling_factors:
        C: 10.0e8 #maybe rescale so results lie roughly in 0-1
        R: 0.01
        C1: 10.0e8
        R1: 0.01
        C2: 10.0e8
        R2: 0.01
        C3: 10.0e8
        R3: 0.01
        A_eff: 100

    Tuning:
      perform: True
      study_name: "tuning"
      study_n_trials: 30
      epochs_tuning: 20
      n_jobs: 16
      seeds_per_trial: 5
      hyperparam_ranges:
        learning_rate: [0.0001, 0.005, "NeuralNet", "float"]
        nodes_per_layer/default: [20, 200, "NeuralNet", "int", 20]
        num_layers: [2, 5, "NeuralNet", "int", 1]