import torch
from os.path import dirname as up
import numpy as np
from DataGeneration import generate_weather_based_data
import matplotlib.pyplot as plt  # Corrected import
import Physicals
import DataGeneration
from dantro._import_tools import import_module_from_path, get_from_module
from torchdiffeq import odeint
import pandas as pd
import scipy.optimize as so

# this script contains some test logic that can be freely modified and run directly, independant of the utopya framework.
# it is meant as a quick testbench and does NOT contain ANY logic used in full estimation runs.
# some of this code might be deprecated and not function anymore. Still, it is left in as it helped the last contributor (me)
# with gaining insight into the workings of NeuralABM and the different modules taking part in it.

# a function to optimize a model using the scipy framework and otpimization methods
def scipy_optimization_test(data, physical, dt = 900):

    physical.dt = dt

    initial_condition = data[0, 0, :1, 0]
    xdata=data[0, :, 0, 0].numpy()
    ydata=data[0, :, physical.dynamic_variables:, 0].numpy()
    print(initial_condition)
    def func(inputs, C1, R1, C2, R2, A_eff):
        physical.set_params([C1, R1, C2, R2, A_eff])
        physical.reset()
               
        # Get current initial condition and make traceable
        #initial_condition = data[0]

        # set up loss and time vector, pass external data to ODE object
        time = torch.arange(0, len(inputs), dtype = torch.float32)
        physical.external_data = torch.tensor(inputs).unsqueeze(-1)
        #print(physical.external_data.shape)
        
        # simulate the ODE over horizon
        trajectory = odeint(physical,
                            initial_condition,
                            time,
                            method = 'euler',
                            options={'step_size': 1.0}
                            )
        #print(trajectory.shape)
        return trajectory[:, 0].numpy()
    print(xdata.shape)
    print(ydata.shape)
    p_opt, p_cov = so.curve_fit(f=func,
                            xdata=ydata,
                            ydata=xdata,
                            p0=(1e9, 0.01, 1e9, 0.01, 100)) #needs to be manually adjusted currently

    res1 = pd.DataFrame(index=['C1', 'R1', 'C2', 'R2', 'A_eff'])
    res1['avg'] = p_opt
    res1['std'] = np.diag(p_cov)**0.5
    print(res1)
    plt.plot(xdata, label = "ground truth")
    estim = func(ydata, *p_opt)
    plt.plot(estim, label = "estimated")
    plt.legend()
    print(f"MAE of estimation: {np.mean(np.abs(xdata - estim))}")
    plt.savefig("scipy_estim.pdf")


# plot some data generated by DataGeneration.py
def plot_data(data, dt, cfg):
    
    plot_args = get_from_module(Physicals, name = cfg["model_type"])().plot_args
    # Plot the data
    time_steps = dt * torch.arange(cfg['num_steps'] + 1)
    plt.figure(figsize=(10, 6))
    for i, key in enumerate(plot_args.keys()):
        plt.plot(time_steps, (data[:, i, 0]+plot_args[key]["offset"])*plot_args[key]["multi"], label=key, **plot_args[key]["kwargs"])
    plt.xlabel('Time/s')
    plt.ylabel('Values')
    plt.title('RC Circuit Data')
    plt.legend()
    plt.grid(True)
    #plt.show()

# broad-search parameter space (In this case only one R and one C) and plot Heatmap of evaluation errors
def plot_parameter_space(cfg, dt, res = 100, searchspace = 10, maxloss = 100):
    target = generate_weather_based_data(cfg, dt = dt)
    #plot_data(target, dt, cfg)
    #c_range = torch.linspace(cfg["C"] - cfg["C"]/searchspace*10, cfg["C"] + cfg["C"]/searchspace*20, steps = res)
    c_range = torch.linspace(0.6e7, 0.9e7, steps = res)
    #r_range = torch.linspace(cfg["R"] - cfg["R"]/searchspace, cfg["R"] + cfg["R"]/searchspace, steps = res)
    r_range = torch.linspace(0.00525, 0.00535, steps = res)
    grid1, grid2 = torch.meshgrid(c_range, r_range, indexing = 'ij')
    print(f"Starting to explore parameter space from (C = {grid1.min()}, R = {grid2.min()}) to (C = {grid1.max()}, R = {grid2.max()})")
    loss_func = torch.nn.MSELoss(reduction = "sum")
    physical = get_from_module(Physicals, name = cfg["model_type"])()
    losses = torch.empty_like(grid1)
    dat = target[:,physical.dynamic_variables:,:]
    init = target[:,:physical.dynamic_variables,:][0]
    target = target[:,:physical.dynamic_variables,:]

    for i in range(grid1.shape[0]):
        for j in range(grid1.shape[1]):
            dense = init
            loss = torch.tensor(0.0, requires_grad=False)
            for k in range(cfg["num_steps"]):
                dense = torch.stack(physical.step(dense, dat[k], (grid1[i,j], grid2[i,j]), dt))
                loss = loss+loss_func(dense, target[k])
                if (loss > maxloss):
                    loss = maxloss
                    break
            losses[i,j] = loss
        print(f"explored (C = {grid1[i,j]}, R [{grid2[i,0]}, {grid2[i,-1]}]): {losses[i].mean()}")

    plt.contourf(grid1.numpy(), grid2.numpy(), losses.detach().numpy(), levels=2000)
    plt.colorbar(label='Loss')
    #fig = plt.figure()
    #ax = fig.add_subplot(111, projection='3d')
    #ax.plot_surface(grid1, grid2, losses)
    plt.xlabel('C')
    plt.ylabel('R')
    plt.title('Loss landscape')
    
    plt.show()




    
# some other pure optimizer estimation
def ls_estimation(cfg, data, dt, gamma, num_epochs = 1000):
    physical = get_from_module(Physicals, name = cfg["model_type"])()
    # Assuming data is a torch.Tensor of shape [num_steps, 4, 1] with columns [T_in, T_out, Q_H, Q_O]
    # and dt is defined

    # Initialize parameters
    #params = [torch.tensor([10.0], requires_grad=True) for _ in physical.parameter_names]
    #C = torch.tensor([1.0], requires_grad=True)  # Initial guess and requires_grad=True to enable gradient computation
    #R = torch.tensor([89.0], requires_grad=True)  # Initial guess
    #
    params = []
    scales = []
    for key in physical.parameter_names:
        params.append(torch.tensor([torch.rand(1)], requires_grad=True))
        if key in cfg["scales"]:
            scales.append(cfg["scales"][key])
        else:
            scales.append(1)

    
    

    #params = [torch.tensor([10.0], requires_grad=True) for _ in physical.parameter_names]
    #print(params)
    #scales = [10e6, 10e-3]
    # Optimizer setup
    optimizer = torch.optim.Adam(params, lr=0.002)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=gamma)
    physical.dt = dt
    physical.external_data = data[:, physical.dynamic_variables:]

    time = torch.arange(0, data.shape[0], dtype = torch.float32)

    # Number of epochs for the optimization

    lossFun = torch.nn.MSELoss()

    opt = [10]
    opt.append(params)


    for epoch in range(num_epochs):
        optimizer.zero_grad()  # Clear gradients from the previous iteration
        physical.reset()
        physical.set_params([params[i]*scales[i] for i in range(len(params))])
        loss = 0
        #prms = [params[i]*scales[i] for i in range(len(params))]
        #print(prms)
        
        trajectory = odeint(physical,
                                    data[0][:physical.dynamic_variables],
                                    time,
                                    method = 'euler',
                                    options={'step_size': 1.0}
                                    )
        loss = lossFun(trajectory, data[:, :physical.dynamic_variables])

        if loss < opt[0]:
            opt[0] = loss.item()
            opt[1] = physical.params

        # Compute gradients
        loss.backward()

        # Update parameters
        optimizer.step()
        scheduler.step()

        # Optional: Print loss every 100 epochs
        if epoch % 20 == 0:
            current_lr = scheduler.get_last_lr()[0]
            #print(current_lr)
            print(f'===== Epoch {epoch+1}, lr: {current_lr}, Loss: {loss.item()} =====')
            for i in range(len(params)):
                print(f"{physical.parameter_names[i]} = {scales[i]*params[i].item()} = {scales[i]} * {params[i].item()}")
            print("\n")

    # Final parameters
    print(f'Estimated params: {[f'{physical.parameter_names[i]}: {opt[1][i].item()}' for i in range(len(params))]}')

# some example config
cfg = {
    "model_type": "TiTe",
    "initial_conditions": {
        "T_in": 290,
        "T_out": 270,
        #Heating inside
        "Q_H": 0,
        #Heating outside
        "Q_O": 0
    },
    "store_raw_QSolar": True,
    "effWinArea": 7.89, #[m2] so given Solar radiance [W/m2]*effWinArea = [W]
    "maxHeatingPower": 5000, #[W]
    "controller": "PControl", #PControl, TwoPointControl
    "weather_data": "C:/Users/Timo/Documents/SublimeProjects/neuralabmrc/data/RC_model/weatherData/Munich_5years.mos",
    "num_steps": 1440,  # You can adjust the number of steps as needed (rn: 1/100year in minutes)
    "T_min": 290, #[K]
    "T_max": 294, #[K]
    "C": [7452000, 7500000],         # Capacitance [Ws/°C]
    "R": [0.00529, 0.006],          # Resistance [°C/W]
    "C1": 4896000,
    "R1": 0.00531,
    "C2": 1112400,
    "R2": 0.000639,
    "scales": {"C": 10e6, "R": 10e-3}
    }

#dt = torch.tensor(300) #Time differential in seconds
#data = generate_weather_based_data(cfg, dt=dt)[0] # type: torch.Tensor, size [num_steps, num_variables, 1], Generate synthetic data




#plot_data(data, dt, cfg)
#plt.show()
scipy_optimization_test(DataGeneration.get_RC_circuit_data(data_cfg = {"dt": 900,
                                                                        "load_from_dir":
                                                                            {"path": "C:/Users/Timo/Documents/SublimeProjects/neuralabmrc/data/RC_model/NN_parameter_estimation/8targets_nnEstim_noWin_inhom_noAct/#Uex_0.25#HeaWal_40000#FawSou_0.16#ZonLen_7#Roo_22#Roo_21#Wea_Bratislava#Int_NoActivity/_simulation.csv",
                                                                             "csv_keys": ["thermalZone.TAir", "weaBus.TDryBul", "totalHeatingPower.y", "weaDat.weaBus.HGloHor"],
                                                                             "effWinArea": 1,
                                                                             "subset": 8640}}, # 3monate}))
                                                            h5group = None),
                        get_from_module(Physicals, name = "EffWin.TiTe")(),
                        dt = 900)
#plot_parameter_space(cfg, dt)
#ls_estimation(cfg, data, dt, gamma=1, num_epochs = 500)


